### ISSUE TITLE
Preventing Github tag checkout

### ISSUE THREAD

**Issue by sbaildon** [abiosoft/caddy-git#86]
Hey,

I've a use-case  where;

* I have two repositories
    * project_x
    * A website for project_x
* The website's build steps use Github's API to fetch project_x's most recent release, for download URLs, release date etc
* project_x releases send webhooks to trigger website rebuilds
* `caddy-git` attempts to check out a tag that's present on project_x, but not available to the website's repository

If `caddy-git` didn't attempt to checkout the tag, this workflow would work quite well.

https://github.com/abiosoft/caddy-git/blob/40b1fac37da47a1a76bb23c22eaa7846107267ea/github_hook.go#L146

I'm happy to open a pull request if you're okay for `caddy-git` to disable support for this behaviour, and if you have any ideas on how you'd like to see it implemented?

**Comment by abiosoft** [comment]
What's suppose to be done instead for the webhook ?

**Comment by sBaildon** [comment]
I'd like to see `handleRelease` in `github_hook.go` skip `repo.Branch = release.Release.TagName` and just execute `repo.Pull()`

https://github.com/abiosoft/caddy-git/blob/40b1fac37da47a1a76bb23c22eaa7846107267ea/github_hook.go#L130

**Comment by abiosoft** [comment]
That is not the desired behaviour and would break for everyone else.
Why not simply point caddy-git to project_x or use regular push webhook with specific branch for the website repo.

**Comment by sBaildon** [comment]
I can't go for suggestion 1 because `caddy-git` is already pointed to the website, but that still wouldn't solve the problem because a tag present on project_x repo isn't available on the the website repo.

Suggestion 2 won't work because releases take time to build after the push webhook has fired. `caddy-git` will receive the push webhook and trigger a website build long before the project_x release has been made.

I'd argue that ignoring the `branch` option to pull down the latest tag might go against what people expect? My understanding of the documentation is that; named branch/tag is always pulled, or use {latest} to pull the latest branch/tag. So if I was to use `release` as the value for the `branch` option, `caddy-git` should not attempt to pull anything but the `release` branch?

Regardless, using `interval` works well for my use case 👍
