### ISSUE TITLE
Support for multiple remote urls for a single repo (ssh and https URLs)

### ISSUE THREAD

**Issue by spankie** [abiosoft/caddy-git#90]
When setting up caddy-git in my Caddyfile, the origin remote url was `https` but i added ssh remote url as the repository's url, and this cause an error of (`Another repository exists in the path`).

It would be nice to have caddy-git recognize a repository by its ssh url and https url.

**Comment by abiosoft** [comment]
If you specify private key, you have to use ssh, otherwise use https. I'll see where I can put that in the docs.

Before now, I used to intelligently parse the url and convert it on the fly without the user noticing but due to couple of edge cases, I decided to simply require the user to put the right url format.

**Comment by spankie** [comment]
Alright, Thanks.
